### PR TITLE
Add fixed healthservices to be provided

### LINKED ISSUE #118: Restrict the values of healthservices that the user can input via an enum
User can only select "Blood Test", "Cancer Screening", "Consult", "Vaccination" as a valid health service.

### PR DESCRIPTION
**Pull request by yugan01**
Blood Test, Cancer Screening, vaccination and Consult are the healthservices that the user can choose from.
Fixes #118

### CODE REVIEW

**Review by yuanchengg — APPROVED** [review]
LGTM

File: src/main/java/seedu/address/model/healthservice/HealthService.java [hunk 1]
```diff
@@ -3,14 +3,35 @@
...
+        HealthScreeningServices(String service) {
+            this.service = service;
+        }
+
+        @Override
+        public String toString() {
+            return service;
+        }
+
+    };
```
Comment (DINESH1201) [inline src/main/java/seedu/address/model/healthservice/HealthService.java:34]: Good use of enums Yugan

**Review by DINESH1201 — COMMENTED** [review]
Good idea to make use of enums to classify healthservices
