### PR TITLE
Fix bug in ApptCommand

### LINKED ISSUE #191: Fix bug errors in ApptCommand

### PR DESCRIPTION
**Pull request by jolynleow2301**
Closes #191

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonAdaptedAppt.java [hunk 1]
```diff
@@ -49,9 +61,18 @@ public String getHealthServiceName() {
...
+     * @return Appt
      */
     public Appt toModelType() throws IllegalValueException {
-        return new Appt(LocalDateTime.parse(dateTime), new HealthService(healthService));
+        if (!Appt.isValidDateTime(dateTime)) {
+            logger.severe("Invalid date and time.");
+            throw new IllegalValueException(Appt.DATETIME_MESSAGE_CONSTRAINTS);
+        }
+        
+        if (!HealthService.isValidHealthserviceName(healthService)) {
```
Comment (yuanchengg) [inline src/main/java/seedu/address/storage/JsonAdaptedAppt.java:72]: I think this might lead to a checkstyle error because of trailing whitespace.

**Review by yuanchengg — APPROVED** [review]
LGTM
